name: Build HROB2025
on:
  push:
    branches:
      - master
jobs:
  Build-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run things in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: nixos/nix:latest
          options: -v ${{ github.workspace }}:/code -w /code
          run: |
            nix-env -iA git -A git-lfs -f channel:nixos-unstable
            nix-env -iA cachix -f https://cachix.org/api/v1/install
            cachix use potkavarna-hrob
            nix-shell --run "site build"
      - name: Archive generated site
        uses: actions/upload-artifact@v4
        with:
          name: public-folder
          path: public
  Deploy-Site:
    runs-on: ubuntu-latest
    needs: Build-Site
    steps:
      - name: Download generated site
        uses: actions/download-artifact@v4
        with:
          name: public-folder
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install sshpass
      - name: Deploy site
        env:
            SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
            SFTP_PORT: ${{ secrets.SFTP_PORT }}
            SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
            SFTP_HOSTNAME: ${{ secrets.SFTP_HOSTNAME }}
        run: |
            cd /home/runner/work/hrob2021/hrob2021
            ls -al
            sshpass -p "$SFTP_PASSWORD" scp -P $SFTP_PORT -o StrictHostKeyChecking=no -r . $SFTP_USERNAME@$SFTP_HOSTNAME:.
