name: Build HROB2021
on: [push]
jobs:
  Build-Site:
    runs-on: ubuntu-latest
    container: nixos/nix
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Prepare environment
        run: |
          nix-env -iA git -A git-lfs -f channel:nixos-unstable
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix use tojnar-cz
      - name: Build site
        run: nix-shell --run "site build"
      - name: Archive generated site
        uses: actions/upload-artifact@v2
        with:
          name: public-folder
          path: public
  Deploy-Site:
    runs-on: ubuntu-latest
    needs: Build-Site
    steps:
      - name: Download generated site
        uses: actions/download-artifact@v2
        with:
          name: public-folder
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install sshpass
      - name: Deploy site
        env:
            SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
            SFTP_PORT: ${{ secrets.SFTP_PORT }}
            SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
            SFTP_HOSTNAME: ${{ secrets.SFTP_HOSTNAME }}
        run: |
            sshpass -p "$SFTP_PASSWORD" sftp -P $SFTP_PORT -o StrictHostKeyChecking=no $SFTP_USERNAME@$SFTP_HOSTNAME << EOF
            cd www/hrob2021
            put -r public/*
            exit
            EOF
